### ISSUE TITLE
[APY calc v1] Link to Autobots calculator once it's fixed

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#611]
Follow up with Autobots calculator and see what his intentions are wrt updating it.
Right now, it seems to make some assumptions/show details that may lead to a poor UX.
- Assumes an active reward
- Reward estimates are not yielding the right result

Reference Image:
![image](https://github.com/oceanprotocol/df-web/assets/69865342/3280ff06-1db9-43c2-8e8a-306bfb64deda)

Reference Calculations:
https://docs.google.com/spreadsheets/d/1zzuW5pBbX6j6hZL_XtJDtSR2-rDHa_LGOEwgoQ4D8lk/edit?usp=sharing

Having a calculator up-front-and-center for users would drastically improve the UX when making decisions about how to lock-up their ocean.

### DoD:
- [ ] Autobots or df.oceandao.org has an up-to-date APY/Reward calculator
- [ ] Add hooks on "How to Calculate APY" and point users to calculator

**Comment by Harky911** [comment]
We have resolved an issue that was causing incorrect calculations for veOcean. Initially, when locking for 4 years, the result showed as 10027.473. Now, the problem has been fixed, and it correctly displays 10000 as expected.

**Comment by KatunaNorbert** [comment]
Looks like the calculator is still broken. After clicking calculate the Passive rewards amt is NaN.
